version: '3.8'

services:
  pyspark:
    image: apache/spark:3.5.0
    container_name: pyspark_container
    environment:
      - PYSPARK_PYTHON=python3
    ports:
      - "8080:8080"  # Веб-интерфейс Spark
    volumes:
      - ./app:/opt/spark-apps  # Папка для ваших PySpark-скриптов
      - ./data:/opt/spark-data  # Папка для данных
    command: >
      /bin/bash -c "
      /opt/spark/bin/spark-submit \
      /opt/spark-apps/spark.py
      "